sudo: required
dist: trusty
language: node_js
node_js:
- 8.6.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - google-chrome-stable
    - g++-4.8
  firefox: latest
cache:
  directories:
  - node_modules
env:
  matrix:
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-default
  global:
  - CXX=g++-4.8
  - secure: atbVnEfJRmj6lm5t9voOjr8oVqbUBSmjY1kV4DBynTdBh+n2yZ/D2lcOeEeg4bAPHxUJMI5hxoST6xAMMeLVUhFvC1CDFsogS/B7RSujRLco5EMpX08Y0tAkGbgJLLTeKL1EfWBEQGUfUxJJCVa2xBk0xFKZRKLp/DdvBnA3DeznIs6ut0OcrY71KiBEF2WuTT17QSeVaJnVHz1Wb/25xf0J3nLtjM6LZ1NEdqHUdMBHkc/VVHQE3BqXTw89PnJrQzwyFwRpzYVwL0UAPLoaiwG11FvhBxtPCvhrrX3iDwx7C+HK8vQC62e0mFDHNsffnj1mbVovap6pNA3P/fTLP8cXtHV0gFz7tKYyNFyHAI6JrNTndWwnT4I0Dj05HZ/dOpx3oTrpZZOsRAZhP2VF0508yOLtMPVMBDunToYO2wQI43ri5Hh0s30jM97xEO7w+KRHqr8N5KyL3gn+flgozk+Y+ZKmq8OPcs3xmppWsJdtZx9YNA5xxJiLAGck3uiLdJ2YMC4dg7UtBxo31PslPAcD9XziniG5n6D21++V69r50O2ck1wW27X68d9HFkfw4EiKQrX74oNaUcIr4yoY1XojxVXLA5+4xl1YqLxHkICH2NkFsW1jyGz+weZKCGlbxTe5xPwXyBRq5ra/0c7F1J+k53PomxBfT0yTFf7JBnw=
matrix:
  fast_finish: true
before_install:
- npm config set spin false
- npm install -g pr-bumper@^3.7.0 ciena-devops@^1.0.0
- "$(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh"
install:
- "$(npm root -g)/pr-bumper/.travis/maybe-install.sh"
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- "$(npm root -g)/pr-bumper/.travis/maybe-test.sh"
- ".travis/maybe-bump-version.sh"
after_success:
- ".travis/maybe-publish-coverage.sh"
- ".travis/maybe-publish-gh-pages.sh"
deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: aOoqr2U8oP7LLSmGRqeG88uOAEMxRS/3bWt5R+JwwhFDaRj9V7nGGOiYlz5nRnMDAnXqntgLwwN7lbSKHoA/mp30Hrs3GrenPGESpDWUQEk/vbBN3yWt29ZUFs+RYlDRfgWLPANfjs4SbY1uvEk7As/8a9+F0xjTPW/AJDgQM1Kmv/jmmdpGak47tBmYUfeXmSfBF+4+2vi36XHufoCNUVTvP1mOeU7NwfgSCaYdLeJ10FybLxRpM+t6IBk7PecDFQIxzE1PezSSEyaYnAMNMCSiIVmipYZiTAGKPP//K2QR8YKPYb7Qlb6awXdHf6xrRzUIx1Y3QA8FAxgXcOPgOMaozHqCBlTYc2eky5wEjESqnsX8AJMmnnujesHceAKI9GKRCjCro6kvDLNzvr8ifTfyzD8brsWNxLcuFV1I1At/931XpY7cCtB7Goyzva45dghmCXpDvNgj6QgTP7825VQhgTQq/bsSOws0Ndg7UPK+F/PVlltgGErB/ag/OUxi5dLgea7dHODM/q7/L/SEhAucjoR1Z1e2DLSQFDaD9w8gHtRtH6KIvZEYWP12ovxt1riFVul0yT5JoNVQXqyCXdclTc/vl8N11a7/ROh9SrLRyBU/KREBhTkFWWjP00ynFmS5XOtl/KLnygdh4wnT4vISzsf4uZZ7pbnYTHBBxuk=
  on:
    all_branches: true
    condition: "$EMBER_TRY_SCENARIO = 'ember-default'"
    node: 8.6.0
    tags: true
after_deploy:
- "$(npm root -g)/ciena-devops/scripts/slack/incoming-webhooks/send-message.sh"
notifications:
  slack:
    secure: i4DeSy239IIiW9V0/DAQA/Xv2a6aWVZ8bP4yP5XzsRg1PXPZFIkmHAzHanTFxKYxD2uLNAElQoFftDl8kz6urdM4GqZCAsxpO5DCxd8xYRTtiJWiLE5YzentQhxToz0/bxus+EbCDqoTueuHMTcT2s7L9SrsAUxQnm1AD3ooAByh6GAr0GdWntVkcNu0vjK2Q57i6eR4+svdmkbAGG2hTLlM5RtRG1HYcDYnfmfpL9kCEBFIPrmmkdHmM2/M3g1kmwLGBpJvX3WLv9BnGJn2tMQMP1ETe5pQuCF1e0RfWd6H4ybYF2w1Ss0Tt0n5FX3qfIFwTi98HpHkd4pCdyMrLAyIMi2+3yGYX5ejQpzMmkr5PGHuIW1gCgMW7/drOChlXiS2cvz6HBYONbrXEZP/enHGz9DzsNtXY+vZ3fKjIptC9FeEK6O2JP0VQ8V1MEbnHbcnyhTHwiJA+AbT5XoTErMTqmn+sJr9eZC/tNNMjmsDNlrQle2RCCud53MOuNw6Vt2xrc/JdaWvDAdqBJ/6OfTTlZYD1evTC2BToJojGjEpSsFV3FmuwYalt9cjGPDVPUz0hUMa/mmmK5SjKL+tEs8HvsDVKn4ZgMD41h2xoMR5PK6/E2XynI2aqk66P8MLr0aEYy06ZYhHQpczOucyG//TJwLO736pvyMxOpZDKoM=
